

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      
# move_group:
#   ros__parameters:
#     moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

# moveit_simple_controller_manager:
#   ros__parameters:
#     controller_names:
#       - joint_trajectory_controller

#     joint_trajectory_controller:
#       action_ns: follow_joint_trajectory
#       type: FollowJointTrajectory
#       default: true
#       joints:
#         - joint1
#         - joint2
#         - joint3
#         - joint4
#         - joint5
#         - joint6


# joint_trajectory_controller:
#   type: FollowJointTrajectory
#   action_ns: /joint_trajectory_controller/follow_joint_trajectory
#   default: true
#   joints:
#     - joint1
#     - joint2
#     - joint3
#     - joint4
#     - joint5
#     - joint6
